import { agentPrompts } from './centerAgent';

export const agentConfigs = {
  CLONE_DETECTOR: {
    key: 'CLONE_DETECTOR',
    systemPrompt: agentPrompts.CLONE_DETECTOR,
    name: 'Clone Detector',
    tagline: 'ตรวจจับรูปรถที่ถูก Clone',
    icon: '🔍',
    heroBg: 'bg-gradient-to-br from-violet-50 to-indigo-50',
    iconBg: 'bg-violet-100',
    stepBadge: 'bg-violet-100 text-violet-700',
    description: 'วิเคราะห์ว่ารูปรถของคุณถูกนำไปใช้ซ้ำหรือนำไปขายที่อื่นหรือไม่ โดยใช้ reverse image search และวิเคราะห์ metadata',
    capabilities: [
      'Reverse Image Search บน Google, TinEye, Yandex',
      'วิเคราะห์ EXIF metadata ของรูปภาพ',
      'ค้นหาทะเบียนซ้ำใน Kaidee / One2Car / FB',
      'เปรียบเทียบรูปรถต้นฉบับกับรูปที่พบ',
    ],
    steps: [
      'แจ้งทะเบียนและยี่ห้อรถที่หาย',
      'อัปโหลดหรือส่ง URL รูปรถของคุณ',
      'รอผลการ scan จาก reverse image search',
      'รับรายงานและแผนการดำเนินการ',
    ],
    quickPrompts: [
      'เจอรูปรถผมขายใน Kaidee ทะเบียนต่างออกไป',
      'อยากเช็คว่ารูปรถถูกนำไปใช้ที่ไหนบ้าง',
      'รถหายแต่เจอโพสต์ขายหน้าตาเหมือนกัน',
    ],
    emptyState: 'ส่งรายละเอียดรถที่หายหรือรูปที่น่าสงสัยมาได้เลยครับ',
    inputPlaceholder: 'เช่น พบรูปรถ Honda Civic สีเงินขายใน Kaidee...',
    scope: 'การตรวจจับรูปรถที่ถูก Clone',
  },

  BOT_HUNTER: {
    key: 'BOT_HUNTER',
    systemPrompt: agentPrompts.BOT_HUNTER,
    name: 'Bot Hunter',
    tagline: 'ล่าบัญชีปลอมและ Bot ขายรถ',
    icon: '🤖',
    heroBg: 'bg-gradient-to-br from-rose-50 to-orange-50',
    iconBg: 'bg-rose-100',
    stepBadge: 'bg-rose-100 text-rose-700',
    description: 'ตรวจสอบโพสต์ขายรถและบัญชีผู้ขายว่าเป็น Bot หรือมิจฉาชีพ โดยวิเคราะห์ pattern การโพสต์และสัญญาณอันตราย',
    capabilities: [
      'วิเคราะห์ประวัติและอายุของบัญชีผู้ขาย',
      'ตรวจจับ pattern โพสต์ซ้ำหลายกลุ่ม',
      'เปรียบเทียบราคากับตลาด',
      'ตรวจสอบเลข VIN และทะเบียน',
    ],
    steps: [
      'ส่ง URL โพสต์หรือชื่อบัญชีที่สงสัย',
      'แจ้งราคาที่เสนอขายและยี่ห้อรถ',
      'วิเคราะห์สัญญาณอันตราย 5 ข้อ',
      'รับ risk score และคำแนะนำ',
    ],
    quickPrompts: [
      'เจอโพสต์ขายรถราคาถูกมากน่าสงสัย',
      'บัญชีขายรถสร้างใหม่ไม่ถึง 3 เดือน',
      'โพสต์เดิมซ้ำอยู่หลายกลุ่มใน Facebook',
    ],
    emptyState: 'ส่ง URL โพสต์หรือข้อมูลบัญชีที่น่าสงสัยมาวิเคราะห์ได้เลยครับ',
    inputPlaceholder: 'เช่น URL โพสต์ Facebook หรือรายละเอียดบัญชีผู้ขาย...',
    scope: 'การตรวจจับ Bot และมิจฉาชีพขายรถ',
  },

  DOC_FORGE: {
    key: 'DOC_FORGE',
    systemPrompt: agentPrompts.DOC_FORGE,
    name: 'Doc',
    tagline: 'ตรวจจับเอกสารรถปลอม',
    icon: '📄',
    heroBg: 'bg-gradient-to-br from-amber-50 to-yellow-50',
    iconBg: 'bg-amber-100',
    stepBadge: 'bg-amber-100 text-amber-700',
    description: 'วิเคราะห์ความถูกต้องของเอกสารรถ ตรวจจับเอกสารที่สร้างด้วย AI, Photoshop หรือถูกปลอมแปลง',
    capabilities: [
      'ตรวจ watermark, ฟอนต์, layout เล่มทะเบียน',
      'ตรวจจับ AI-generated document',
      'เช็คใบเสร็จกับกรมขนส่ง',
      'วิเคราะห์ pixel artifact รอบตัวอักษร',
    ],
    steps: [
      'แจ้งว่าเอกสารใดที่น่าสงสัย',
      'ส่งรูปเอกสารหรืออธิบายความผิดปกติ',
      'รับ checklist การตรวจสอบ',
      'ดำเนินการตรวจสอบกับหน่วยงาน',
    ],
    quickPrompts: [
      'เล่มทะเบียนรถดูไม่ปกติ ฟอนต์แปลกๆ',
      'ตำรวจแจ้งว่ารถผมไปทำผิด ทั้งที่จอดอยู่บ้าน',
      'อยากตรวจว่าเอกสารซื้อขายรถเป็นของจริงไหม',
    ],
    emptyState: 'ส่งรายละเอียดเอกสารที่น่าสงสัยหรืออธิบายความผิดปกติมาได้เลยครับ',
    inputPlaceholder: 'เช่น เล่มทะเบียนรถสีหมึกไม่สม่ำเสมอ ตัวเลขดูพิมพ์ซ้อน...',
    scope: 'การตรวจจับเอกสารรถปลอม',
  },

  SCRAPER: {
    key: 'SCRAPER',
    systemPrompt: agentPrompts.SCRAPER,
    name: 'Scraper',
    tagline: 'กวาดหาข้อมูลรถทั่ว Network',
    icon: '🌐',
    heroBg: 'bg-gradient-to-br from-teal-50 to-cyan-50',
    iconBg: 'bg-teal-100',
    stepBadge: 'bg-teal-100 text-teal-700',
    description: 'ค้นหาข้อมูลรถจากหลายแพลตฟอร์มพร้อมกัน สร้าง search query ที่มีประสิทธิภาพ และระบุแหล่งที่ควรตรวจสอบ',
    capabilities: [
      'สร้าง search query สำหรับ Kaidee, One2Car, FB',
      'ค้นหาในกระทู้ Pantip แจ้งรถหาย',
      'ตรวจสอบทะเบียนกับกรมขนส่ง',
      'วางแผนการค้นหาอย่างเป็นระบบ',
    ],
    steps: [
      'แจ้งทะเบียน ยี่ห้อ รุ่น สีรถ',
      'ระบุช่วงเวลาที่หายหรือน่าสงสัย',
      'รับ search plan ครอบคลุมทุกแพลตฟอร์ม',
      'ลงมือค้นตาม query ที่ได้รับ',
    ],
    quickPrompts: [
      'อยากหาว่ารถของผมไปอยู่ที่ไหน',
      'ช่วยสร้าง search query หารถ Toyota Camry สีขาว',
      'อยากค้นหาทะเบียน กข 1234 ในทุกเว็บขายรถ',
    ],
    emptyState: 'แจ้งทะเบียน ยี่ห้อ และรุ่นรถ แล้วผมจะสร้างแผนค้นหาให้ครับ',
    inputPlaceholder: 'เช่น ช่วยหา Honda Jazz สีเทา ทะเบียน กข-5678...',
    scope: 'การค้นหาและ scrape ข้อมูลรถ',
  },
};
